name: proyectocompras
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.2.1
  image_picker: ^1.0.4
  file_picker: ^10.3.0
  flutter_slidable: ^3.0.0
  flutter_speed_dial: ^7.0.0
  share_plus: ^10.0.2
  awesome_snackbar_content: ^0.1.7
  path_provider: ^2.1.3
  path: ^1.2.0
  http: ^1.2.0
  html: ^0.15.4
  super_clipboard: ^0.9.1
  mobile_scanner: ^6.0.2
  openfoodfacts: ^3.2.0
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2

dependency_overrides:
  awesome_snackbar_content: ^0.1.7

  path: ^1.8.3
  shared_preferences: ^2.4.0
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  assets:
    - .env
  generate: true
  uses-material-design: true
